# Makefile generated by imake - do not edit!
# $TOG: imake.c /main/97 1997/06/20 20:23:51 kaleb $

# ----------------------------------------------------------------------
# Makefile generated from "Imake.tmpl" and <Imakefile>
# $TOG: Imake.tmpl /main/245 1997/05/20 10:05:47 kaleb $
#
#
#
#
# $XFree86: xc/config/cf/Imake.tmpl,v 3.32.2.5 1997/07/06 07:27:59 dawes Exp $
# ----------------------------------------------------------------------

all::

.SUFFIXES: .i

# $TOG: Imake.cf /main/28 1997/06/25 08:31:36 barstow $
# $XFree86: xc/config/cf/Imake.cf,v 3.34.2.3 1997/07/27 02:41:02 dawes Exp $

# -----------------------------------------------------------------------
# site-specific configuration parameters that need to come before
# the platform-specific parameters - edit site.def to change

# site:  $XConsortium: site.def /main/revisionist/4 1996/12/31 08:02:07 kaleb $
# site:  $XFree86: xc/config/cf/site.def,v 3.17.2.1 1997/06/22 10:32:21 dawes Exp $

# $XFree86: xc/config/cf/xf86site.def,v 3.101.2.11 1997/06/22 10:32:22 dawes Exp $

# ----------------------------------------------------------------------
# platform-specific configuration parameters - edit linux.cf to change

# platform:  $TOG: linux.cf /main/36 1997/06/16 22:21:03 kaleb $
# platform:  $XFree86: xc/config/cf/linux.cf,v 3.57.2.10 1997/07/28 14:17:25 dawes Exp $

# operating system:  Linux 2.1.61 i586 [ELF] (2.1.61)
# libc:	(5.4.38)
# binutils: 	(28)

# $XConsortium: lnxLib.rules /main/13 1996/09/28 16:11:01 rws $
# $XFree86: xc/config/cf/lnxLib.rules,v 3.28.2.3 1997/06/22 10:32:20 dawes Exp $

# $XFree86: xc/config/cf/xfree86.cf,v 3.129.2.14 1997/07/06 07:28:00 dawes Exp $

# $XConsortium: xfree86.cf /main/34 1996/12/06 11:45:18 rws $

LINKKITDIR = $(USRLIBDIR)/Server
XF98LINKKITDIR = $(USRLIBDIR)/Server

       XF86SRC = $(SERVERSRC)/hw/xfree86
  XF86ACCELSRC = $(XF86SRC)/accel
    XF86COMSRC = $(XF86SRC)/common
 XF86CONFIGSRC = $(XF86COMSRC)
     XF86HWSRC = $(XF86SRC)/common_hw
     XF86OSSRC = $(XF86SRC)/os-support
  VGADRIVERSRC = $(XF86SRC)/vga256/drivers
VGA16DRIVERSRC = $(XF86SRC)/vga16/drivers
 VGA2DRIVERSRC = $(XF86SRC)/vga2/drivers
 MONODRIVERSRC = $(XF86SRC)/mono/drivers
   S3DRIVERSRC = $(XF86SRC)/accel/s3/drivers
  S3VDRIVERSRC = $(XF86SRC)/accel/s3_virge/drivers

       XF68SRC = $(SERVERSRC)/hw/xfree68
    XF68COMSRC = $(XF68SRC)/common
 XF68CONFIGSRC = $(XF68COMSRC)
     XF68OSSRC = $(XF68SRC)/os-support

           XF98SRC = $(SERVERSRC)/hw/xfree98
      XF98ACCELSRC = $(XF98SRC)/accel
        XF98COMSRC = $(XF98SRC)/common
     XF98CONFIGSRC = $(XF98COMSRC)
         XF98HWSRC = $(XF98SRC)/common_hw/generic
      XF98HWNECSRC = $(XF98SRC)/common_hw/nec
    XF98HWPWSKBSRC = $(XF98SRC)/common_hw/pwskb
     XF98HWPWLBSRC = $(XF98SRC)/common_hw/pwlb
    XF98HWGA968SRC = $(XF98SRC)/common_hw/ga968
         XF98OSSRC = $(XF98SRC)/os-support
  XF98VGADRIVERSRC = $(XF98SRC)/vga256/drivers
XF98VGA16DRIVERSRC = $(XF98SRC)/vga16/drivers
 XF98VGA2DRIVERSRC = $(XF98SRC)/vga2/drivers
 XF98MONODRIVERSRC = $(XF98SRC)/mono/drivers
XF98NECS3DRIVERSRC = $(XF98SRC)/accel/s3nec/drivers
XF98PWSKBDRIVERSRC = $(XF98SRC)/accel/s3pwskb/drivers
 XF98PWLBDRIVERSRC = $(XF98SRC)/accel/s3pwlb/drivers
XF98GA968DRIVERSRC = $(XF98SRC)/accel/s3ga968/drivers

        XFREE86DOCDIR = $(LIBDIR)/doc
      XFREE86PSDOCDIR = $(XFREE86DOCDIR)/PostScript
    XFREE86HTMLDOCDIR = $(XFREE86DOCDIR)/html
XFREE86JAPANESEDOCDIR = $(XFREE86DOCDIR)/Japanese

# $XConsortium: xf86.rules /main/9 1996/10/31 14:54:26 kaleb $
# $XFree86: xc/config/cf/xf86.rules,v 3.16.2.1 1997/05/18 12:00:01 dawes Exp $

# ----------------------------------------------------------------------
# site-specific configuration parameters that go after
# the platform-specific parameters - edit site.def to change

# site:  $XConsortium: site.def /main/revisionist/4 1996/12/31 08:02:07 kaleb $
# site:  $XFree86: xc/config/cf/site.def,v 3.17.2.1 1997/06/22 10:32:21 dawes Exp $

# ---------------------------------------------------------------------
# Imake rules for building libraries, programs, scripts, and data files
# rules:  $TOG: Imake.rules /main/222 1997/07/17 20:04:40 kaleb $
# rules:  $XFree86: xc/config/cf/Imake.rules,v 3.33.2.5 1997/07/19 04:59:07 dawes Exp $

 _NULLCMD_ = @ echo -n

TKLIBNAME =

TKLIBDIR =

TCLLIBNAME =

TCLIBDIR =

          PATHSEP = /
            SHELL = /bin/sh

              TOP = .
      CURRENT_DIR = .

            IMAKE = imake
           DEPEND = gccmakedep
        MKDIRHIER = mkdir -p
    EXPORTLISTGEN =
        CONFIGSRC = $(TOP)/config
         IMAKESRC = $(CONFIGSRC)/imake
        DEPENDSRC = $(CONFIGSRC)/util

          INCROOT = /usr/X11R6/include
        USRLIBDIR = /usr/X11R6/lib
        VARLIBDIR = /var/lib
         SHLIBDIR = /usr/X11R6/lib
       LINTLIBDIR = $(USRLIBDIR)/lint
          MANPATH = /usr/X11R6/man
    MANSOURCEPATH = $(MANPATH)/man
           MANDIR = $(MANSOURCEPATH)1
        LIBMANDIR = $(MANSOURCEPATH)3
       FILEMANDIR = $(MANSOURCEPATH)5

               AR = ar clq
  BOOTSTRAPCFLAGS =
               CC = gcc
               AS = as

.SUFFIXES: .cc

              CXX = c++
          CXXFILT = c++filt
           CXXLIB =
    CXXDEBUGFLAGS = -O2
CXXDEPENDINCLUDES =
 CXXEXTRA_DEFINES =
CXXEXTRA_INCLUDES =
   CXXSTD_DEFINES = -Dlinux -D__i386__ -D_POSIX_SOURCE -D_BSD_SOURCE -D_SVID_SOURCE -DX_LOCALE $(CXXPROJECT_DEFINES)
       CXXOPTIONS =
      CXXINCLUDES = $(INCLUDES) $(TOP_INCLUDES) $(CXXEXTRA_INCLUDES)
       CXXDEFINES = $(CXXINCLUDES) $(CXXSTD_DEFINES) $(THREADS_CXXDEFINES) $(CXXEXTRA_DEFINES) $(DEFINES)
         CXXFLAGS = $(CXXDEBUGFLAGS) $(CXXOPTIONS) $(THREADS_CXXFLAGS) $(CXXDEFINES)

         COMPRESS = compress
          GZIPCMD = gzip
              CPP = /lib/cpp $(STD_CPP_DEFINES)
    PREPROCESSCMD = gcc -E $(STD_CPP_DEFINES)
          INSTALL = install
     INSTALLFLAGS = -c
               LD = ld
              LEX = flex -l
           LEXLIB = -lfl
             YACC = bison -y
           CCYACC = bison -y
             LINT = lint
      LINTLIBFLAG = -C
         LINTOPTS = -axz
               LN = ln -s
             MAKE = make
               MV = mv -f
               CP = cp

           RANLIB = ranlib
  RANLIBINSTFLAGS =

               RM = rm -f
        MANSUFFIX = 1x
     LIBMANSUFFIX = 3x
    FILEMANSUFFIX = 5x
            TROFF = psroff
            NROFF = nroff
         MSMACROS = -ms
        MANMACROS = -man
              TBL = tbl
              EQN = eqn
             NEQN = neqn
              COL = col

            DVIPS = dvips
            LATEX = latex

     STD_INCLUDES =
  STD_CPP_DEFINES = -traditional -Dlinux -D__i386__ -D_POSIX_SOURCE -D_BSD_SOURCE -D_SVID_SOURCE -DX_LOCALE $(PROJECT_DEFINES)
      STD_DEFINES = -Dlinux -D__i386__ -D_POSIX_SOURCE -D_BSD_SOURCE -D_SVID_SOURCE -DX_LOCALE $(PROJECT_DEFINES)
 EXTRA_LOAD_FLAGS =
  EXTRA_LDOPTIONS =
  EXTRA_LIBRARIES =
             TAGS = ctags

   PARALLELMFLAGS =

    SHAREDCODEDEF =
         SHLIBDEF =

     SHLIBLDFLAGS = -shared

         PICFLAGS = -fPIC

      CXXPICFLAGS = -fPIC

    PROTO_DEFINES = -DFUNCPROTO=15 -DNARROWPROTO

     INSTPGMFLAGS = -s

     INSTBINFLAGS = -m 0755
     INSTUIDFLAGS = -m 4711
     INSTLIBFLAGS = -m 0644
     INSTINCFLAGS = -m 0444
     INSTMANFLAGS = -m 0444
     INSTDATFLAGS = -m 0444
    INSTKMEMFLAGS = -m 4711

      PROJECTROOT = /usr/X11R6

      CDEBUGFLAGS = -O2
        CCOPTIONS =

      ALLINCLUDES = $(INCLUDES) $(EXTRA_INCLUDES) $(TOP_INCLUDES) $(STD_INCLUDES)
       ALLDEFINES = $(ALLINCLUDES) $(STD_DEFINES) $(EXTRA_DEFINES) $(PROTO_DEFINES) $(THREADS_DEFINES) $(DEFINES)
           CFLAGS = $(CDEBUGFLAGS) $(CCOPTIONS) $(THREADS_CFLAGS) $(ALLDEFINES)
        LINTFLAGS = $(LINTOPTS) -DLINT $(ALLDEFINES) $(DEPEND_DEFINES)
         LDPRELIB = -L$(USRLIBDIR)
        LDPOSTLIB =
        LDOPTIONS = $(CDEBUGFLAGS) $(CCOPTIONS)  $(EXTRA_LDOPTIONS) $(THREADS_LDFLAGS) $(LOCAL_LDFLAGS) $(LDPRELIBS)
     CXXLDOPTIONS = $(CXXDEBUGFLAGS) $(CXXOPTIONS) $(EXTRA_LDOPTIONS) $(THREADS_CXXLDFLAGS) $(LOCAL_LDFLAGS) $(LDPRELIBS)

           LDLIBS = $(LDPOSTLIBS) $(THREADS_LIBS) $(SYS_LIBRARIES) $(EXTRA_LIBRARIES)

           CCLINK = $(CC)

          CXXLINK = $(CXX)

     LDSTRIPFLAGS = -x
   LDCOMBINEFLAGS = -r
      DEPENDFLAGS =

# Not sure this belongs here
         TKLIBDIR =
         TKINCDIR =
        TKLIBNAME =
        TKLIBRARY = -L$(TKLIBDIR) -l$(TKLIBNAME)
        TCLLIBDIR =
        TCLINCDIR =
       TCLLIBNAME =
       TCLLIBRARY = -L$(TCLLIBDIR) -l$(TCLLIBNAME)

        MACROFILE = linux.cf
           RM_CMD = $(RM)

    IMAKE_DEFINES =

         IRULESRC = $(CONFIGDIR)
        IMAKE_CMD = $(IMAKE) -DUseInstalled -I$(IRULESRC) $(IMAKE_DEFINES)

     ICONFIGFILES = $(IRULESRC)/Imake.tmpl $(IRULESRC)/X11.tmpl 			$(IRULESRC)/site.def $(IRULESRC)/$(MACROFILE) 			$(IRULESRC)/xfree86.cf $(IRULESRC)/xf86.rules $(IRULESRC)/xf86site.def $(IRULESRC)/host.def $(EXTRA_ICONFIGFILES)

# $TOG: X11.rules /main/4 1997/04/30 15:23:24 kaleb $

# ----------------------------------------------------------------------
# X Window System Build Parameters and Rules
# $TOG: X11.tmpl /main/292 1997/05/20 10:05:59 kaleb $
#
#
#
#
# $XFree86: xc/config/cf/X11.tmpl,v 1.8.2.3 1997/05/21 15:02:13 dawes Exp $

# -----------------------------------------------------------------------
# X Window System make variables; these need to be coordinated with rules

             XTOP = $(TOP)
           BINDIR = /usr/X11R6/bin
     BUILDINCROOT = $(TOP)/exports
      BUILDINCDIR = $(BUILDINCROOT)/include
      BUILDINCTOP = ../..
      BUILDLIBDIR = $(TOP)/exports/lib
      BUILDLIBTOP = ../..
      BUILDBINDIR = $(TOP)/exports/bin
      BUILDBINTOP = ../..
    XBUILDINCROOT = $(XTOP)/exports
     XBUILDINCDIR = $(XBUILDINCROOT)/include/X11
     XBUILDINCTOP = ../../..
     XBUILDBINDIR = $(XBUILDINCROOT)/bin
           INCDIR = $(INCROOT)
           ADMDIR = /usr/adm
           LIBDIR = $(USRLIBDIR)/X11
   TOP_X_INCLUDES = -I$(XPROJECTROOT)/include

          FONTDIR = $(LIBDIR)/fonts
         XINITDIR = $(LIBDIR)/xinit
           XDMDIR = $(LIBDIR)/xdm
        XDMVARDIR = $(VARLIBDIR)/xdm
           TWMDIR = $(LIBDIR)/twm
           XSMDIR = $(LIBDIR)/xsm
           NLSDIR = $(LIBDIR)/nls
       XLOCALEDIR = $(LIBDIR)/locale
        PEXAPIDIR = $(LIBDIR)/PEX
      LBXPROXYDIR = $(LIBDIR)/lbxproxy
  PROXYMANAGERDIR = $(LIBDIR)/proxymngr
        XPRINTDIR = $(LIBDIR)
      XAPPLOADDIR = $(LIBDIR)/app-defaults
       FONTCFLAGS = -t

     INSTAPPFLAGS = $(INSTDATFLAGS)

              RGB = rgb
            FONTC = bdftopcf
        MKFONTDIR = mkfontdir

       DOCUTILSRC = $(XTOP)/doc/util
        CLIENTSRC = $(TOP)/clients
          DEMOSRC = $(TOP)/demos
       XDOCMACROS = $(DOCUTILSRC)/macros.t
       XIDXMACROS = $(DOCUTILSRC)/indexmacros.t
       PROGRAMSRC = $(TOP)/programs
           LIBSRC = $(XTOP)/lib
          FONTSRC = $(XTOP)/fonts
       INCLUDESRC = $(BUILDINCROOT)/include
      XINCLUDESRC = $(INCLUDESRC)/X11
        SERVERSRC = $(XTOP)/programs/Xserver
       CONTRIBSRC = $(XTOP)/../contrib
   UNSUPPORTEDSRC = $(XTOP)/unsupported
           DOCSRC = $(XTOP)/doc
           RGBSRC = $(XTOP)/programs/rgb
      BDFTOPCFSRC = $(PROGRAMSRC)/bdftopcf
     MKFONTDIRSRC = $(PROGRAMSRC)/mkfontdir
    FONTSERVERSRC = $(PROGRAMSRC)/xfs
       FONTINCSRC = $(XTOP)/include/fonts
        EXTINCSRC = $(XTOP)/include/extensions
     TRANSCOMMSRC = $(LIBSRC)/xtrans
   TRANS_INCLUDES = -I$(TRANSCOMMSRC)

       XENVLIBDIR = $(USRLIBDIR)
   CLIENTENVSETUP = LD_LIBRARY_PATH=$(XENVLIBDIR)

# $XConsortium: lnxLib.tmpl,v 1.5 95/01/11 21:44:44 kaleb Exp $
# $XFree86: xc/config/cf/lnxLib.tmpl,v 3.9 1996/02/24 04:32:52 dawes Exp $

          XLIBSRC = $(LIBSRC)/X11

SOXLIBREV = 6.1
DEPXONLYLIB =
XONLYLIB =  -lX11

LINTXONLY = $(LINTLIBDIR)/llib-lX11.ln

         XLIBONLY = $(XONLYLIB)

      XEXTLIBSRC = $(LIBSRC)/Xext

SOXEXTREV = 6.3
DEPEXTENSIONLIB =
EXTENSIONLIB =  -lXext

LINTEXTENSION = $(LINTLIBDIR)/llib-lXext.ln

LINTEXTENSIONLIB = $(LINTEXTENSION)
          DEPXLIB = $(DEPEXTENSIONLIB) $(DEPXONLYLIB)
             XLIB = $(EXTENSIONLIB) $(XONLYLIB)
         LINTXLIB = $(LINTXONLYLIB)

    XSSLIBSRC = $(LIBSRC)/Xss

DEPXSSLIB = $(USRLIBDIR)/libXss.a
XSSLIB =  -lXss

LINTXSS = $(LINTLIBDIR)/llib-lXss.ln

    XXF86MISCLIBSRC = $(LIBSRC)/Xxf86misc

DEPXXF86MISCLIB = $(USRLIBDIR)/libXxf86misc.a
XXF86MISCLIB =  -lXxf86misc

LINTXXF86MISC = $(LINTLIBDIR)/llib-lXxf86misc.ln

    XXF86VMLIBSRC = $(LIBSRC)/Xxf86vm

DEPXXF86VMLIB = $(USRLIBDIR)/libXxf86vm.a
XXF86VMLIB =  -lXxf86vm

LINTXXF86VM = $(LINTLIBDIR)/llib-lXxf86vm.ln

    XXF86DGALIBSRC = $(LIBSRC)/Xxf86dga

DEPXXF86DGALIB = $(USRLIBDIR)/libXxf86dga.a
XXF86DGALIB =  -lXxf86dga

LINTXXF86DGA = $(LINTLIBDIR)/llib-lXxf86dga.ln

    XDPMSLIBSRC = $(LIBSRC)/Xdpms

DEPXDPMSLIB = $(USRLIBDIR)/libXdpms.a
XDPMSLIB =  -lXdpms

LINTXDPMS = $(LINTLIBDIR)/llib-lXdpms.ln

         XAUTHSRC = $(LIBSRC)/Xau

DEPXAUTHLIB = $(USRLIBDIR)/libXau.a
XAUTHLIB =  -lXau

LINTXAUTH = $(LINTLIBDIR)/llib-lXau.ln

      XDMCPLIBSRC = $(LIBSRC)/Xdmcp

DEPXDMCPLIB = $(USRLIBDIR)/libXdmcp.a
XDMCPLIB =  -lXdmcp

LINTXDMCP = $(LINTLIBDIR)/llib-lXdmcp.ln

           XMUSRC = $(LIBSRC)/Xmu

SOXMUREV = 6.0
DEPXMULIB =
XMULIB =  -lXmu

LINTXMU = $(LINTLIBDIR)/llib-lXmu.ln

       OLDXLIBSRC = $(LIBSRC)/oldX

DEPOLDXLIB = $(USRLIBDIR)/liboldX.a
OLDXLIB =  -loldX

LINTOLDX = $(LINTLIBDIR)/llib-loldX.ln

         XPLIBSRC = $(LIBSRC)/Xp

SOXPREV = 6.2
DEPXPLIB =
XPLIB =  -lXp

LINTXP = $(LINTLIBDIR)/llib-lXp.ln

       TOOLKITSRC = $(LIBSRC)/Xt

SOXTREV = 6.0
DEPXTOOLONLYLIB =
XTOOLONLYLIB =  -lXt

LINTXTOOLONLY = $(LINTLIBDIR)/llib-lXt.ln

      DEPXTOOLLIB = $(DEPXTOOLONLYLIB) $(DEPSMLIB) $(DEPICELIB)
         XTOOLLIB = $(XTOOLONLYLIB) $(SMLIB) $(ICELIB)
     LINTXTOOLLIB = $(LINTXTOOLONLYLIB)

       XALIBSRC = $(LIBSRC)/Xa

SOXAREV = 1.0
DEPXALIB =
XALIB =  -lXa

LINTXA = $(LINTLIBDIR)/llib-lXa.ln

       AWIDGETSRC = $(LIBSRC)/Xaw

SOXAWREV = 6.1
DEPXAWLIB =
XAWLIB =  -lXaw

LINTXAW = $(LINTLIBDIR)/llib-lXaw.ln

         XILIBSRC = $(LIBSRC)/Xi

SOXINPUTREV = 6.0
DEPXILIB =
XILIB =  -lXi

LINTXI = $(LINTLIBDIR)/llib-lXi.ln

      XTESTLIBSRC = $(LIBSRC)/Xtst

SOXTESTREV = 6.1
DEPXTESTLIB =
XTESTLIB =  -lXtst

LINTXTEST = $(LINTLIBDIR)/llib-lXtst.ln

        PEXLIBSRC = $(LIBSRC)/PEX5

SOPEXREV = 6.0
DEPPEXLIB =
PEXLIB =  -lPEX5

LINTPEX = $(LINTLIBDIR)/llib-lPEX5.ln

        XIELIBSRC = $(LIBSRC)/XIE

SOXIEREV = 6.0
DEPXIELIB =
XIELIB =  -lXIE

LINTXIE = $(LINTLIBDIR)/llib-lXIE.ln

      PHIGSLIBSRC = $(LIBSRC)/PHIGS

DEPPHIGSLIB = $(USRLIBDIR)/libphigs.a
PHIGSLIB =  -lphigs

LINTPHIGS = $(LINTLIBDIR)/llib-lphigs.ln

DEPXBSDLIB = $(USRLIBDIR)/libXbsd.a
XBSDLIB =  -lXbsd

LINTXBSD = $(LINTLIBDIR)/llib-lXbsd.ln

           ICESRC = $(LIBSRC)/ICE

SOICEREV = 6.3
DEPICELIB =
ICELIB =  -lICE

LINTICE = $(LINTLIBDIR)/llib-lICE.ln

            SMSRC = $(LIBSRC)/SM

SOSMREV = 6.0
DEPSMLIB =
SMLIB =  -lSM

LINTSM = $(LINTLIBDIR)/llib-lSM.ln

           XKEYSRC = $(LIBSRC)/Xkey

SOXKEYREV = 6.0
DEPXKEYLIB =
XKEYLIB =  -lXkey

LINTXKEY = $(LINTLIBDIR)/llib-lXkey.ln

         FSLIBSRC = $(LIBSRC)/FS

DEPFSLIB = $(USRLIBDIR)/libFS.a
FSLIB =  -lFS

LINTFS = $(LINTLIBDIR)/llib-lFS.ln

         FONTLIBSRC = $(LIBSRC)/font

DEPFONTLIB = $(USRLIBDIR)/libfont.a
FONTLIB =  -lfont

LINTFONT = $(LINTLIBDIR)/llib-lfont.ln

          XPMLIBSRC = $(LIBSRC)/Xpm

DEPXPMLIB = $(USRLIBDIR)/libXpm.a
XPMLIB =  -lXpm

LINTXPM = $(LINTLIBDIR)/llib-lXpm.ln

    XKBFILELIBSRC = $(LIBSRC)/xkbfile

DEPXKBFILELIB = $(USRLIBDIR)/libxkbfile.a
XKBFILELIB =  -lxkbfile

LINTXKBFILE = $(LINTLIBDIR)/llib-lxkbfile.ln

     XKBCOMPCMD = xkbcomp

    XKBUILIBSRC = $(LIBSRC)/xkbui

DEPXKBUILIB = $(USRLIBDIR)/libxkbui.a
XKBUILIB =  -lxkbui

LINTXKBUI = $(LINTLIBDIR)/llib-lxkbui.ln

          DEPLIBS = $(DEPXAWLIB) $(DEPXMULIB) $(DEPXTOOLLIB) $(DEPXLIB)

         DEPLIBS1 = $(DEPLIBS)
         DEPLIBS2 = $(DEPLIBS)
         DEPLIBS3 = $(DEPLIBS)
         DEPLIBS4 = $(DEPLIBS)
         DEPLIBS5 = $(DEPLIBS)
         DEPLIBS6 = $(DEPLIBS)
         DEPLIBS7 = $(DEPLIBS)
         DEPLIBS8 = $(DEPLIBS)
         DEPLIBS9 = $(DEPLIBS)
         DEPLIBS10 = $(DEPLIBS)

# Redefining MKDIRHIER if necessary
# It should go away if the definition of MKDIRHIER
# is protected by #ifndef in Project.tmpl

              XTOP = $(TOP)
              MTOP = $(TOP)
     XBUILDINCROOT = $(XTOP)/exports
      XBUILDINCDIR = $(XBUILDINCROOT)/X11

         IMAKE_CMD = $(IMAKE) -DUseInstalled -DUseInstalledMotif -I$(IRULESRC) $(IMAKE_DEFINES)

         CLIENTSRC = $(XTOP)/clients
           DEMOSRC = $(XTOP)/demos
            LIBSRC = $(XTOP)/lib
           FONTSRC = $(XTOP)/fonts
        INCLUDESRC = $(XTOP)/X11
         SERVERSRC = $(XTOP)/server
           UTILSRC = $(XTOP)/util
        EXAMPLESRC = $(XTOP)/examples
            DOCSRC = $(XTOP)/doc
            RGBSRC = $(XTOP)/rgb
      EXTENSIONSRC = $(XTOP)/extensions

      TOP_INCLUDES = -I$(INCROOT)

      UIL_INCLUDES = -I$(USRINCDIR)/uil

     XPM_DEFINES =

     XPM_TOP = $(PROJECTROOT)

     XPM_INCLUDES	= -I$(XPM_TOP)/include/X11

     XPM_LIBS           = $(XPMLIB)

      USRINCDIR = /usr/X11R6/include
         UIDDIR = $(LIBDIR)/uid
        TESTSRC = $(MTOP)/tests
        TESTLIB = $(TESTSRC)/lib
  GENERALSRCLIB = $(TESTSRC)/General/lib
  GENERALSRCBIN = $(TESTSRC)/General/bin
   MANUALSRCLIB = $(TESTSRC)/Manual/lib
   MANUALSRCBIN = $(TESTSRC)/Manual/bin
     AUTOSRCLIB = $(TESTSRC)/Auto/lib
     AUTOSRCBIN = $(TESTSRC)/Auto/bin
       COMMONPP = $(GENERALSRCBIN)/Commonpp
         GENRUN = $(GENERALSRCBIN)/Genrun
         MANRUN = $(GENERALSRCBIN)/Manrun

     TESTCOMSRC = $(MANUALSRCLIB)/Common

    MTOOLKITSRC = $(TOOLKITSRC)
    MINCLUDESRC = $(MTOP)/X11
        MLIBSRC = $(MTOP)/lib
     MCLIENTSRC = $(MTOP)/clients
       MDEMOSRC = $(MTOP)/demos
     MWIDGETSRC = $(MLIBSRC)/Xm
   MRESOURCESRC = $(MLIBSRC)/Mrm
         UILSRC = $(MCLIENTSRC)/uil

            UIL = _MUse(uil,$(UILSRC)/uil)
         DEPUIL = _MUseCat($(BINDIR),$(UILSRC),/uil)

   XMEXTRA_LIBS =

SOXMREV = 2.0
DEPXMONLYLIB =
XMONLYLIB =  -lXm

LINTXMONLY = $(LINTLIBDIR)/llib-lXm.ln

   XMLIBONLY = $(XMONLYLIB)
   XMLIB = $(XMLIBONLY) $(XPM_LIBS)

   DEPXMLIB = $(DEPXMONLYLIB)

SOMRMREV = 2.0
DEPMRESOURCELIB =
MRESOURCELIB =  -lMrm

LINTMRESOURCE = $(LINTLIBDIR)/llib-lMrm.ln

SOUILREV = 2.0
DEPUILLIB =
UILLIB =  -lUil

LINTUIL = $(LINTLIBDIR)/llib-lUil.ln

SOMCOMMONREV = 2.0
DEPTESTCOMLIB =
TESTCOMLIB =  -lCommon

LINTTESTCOM = $(LINTLIBDIR)/llib-lCommon.ln

TESTUILCOMLIB = $(TESTCOMSRC)/libCommonUil.a

  LINTMRESOURCE = $(MRESOURCESRC)/libMrm.a
LINTXMWIDGETLIB = $(MWIDGETSRC)/llib-l/Xm.ln
     LINTXMTOOL = $(MTOOLKITSRC)/llib-lXt.ln
     LINTUILLIB = $(UILSRC)/llib-lUil.ln

      YACCFLAGS =
       UILFLAGS =

         RM_CMD = $(RM) *.CKP *.ln *.BAK *.bak *.o core errs ,* *~ *.a .emacs_* tags TAGS make.log MakeOut  *.Dat

    STD_DEFINES = -Dlinux -D__i386__ -D_POSIX_SOURCE -D_BSD_SOURCE -D_SVID_SOURCE -DX_LOCALE  -DNO_MESSAGE_CATALOG

        DEPLIBS = $(DEPXMLIB) $(DEPXTOOLLIB) $(DEPXLIB)

        DEPLIBS1 = $(DEPLIBS)
        DEPLIBS2 = $(DEPLIBS)
        DEPLIBS3 = $(DEPLIBS)

XMULIBONLY = -lXmu
XMULIB = $(XMULIBONLY) $(XTOOLLIB) $(XLIB)

        CONFIGDIR = $(LIBDIR)/config

    USRLIBDIRPATH = $(USRLIBDIR)
        LDPRELIBS = -L$(USRLIBDIR)
       LDPOSTLIBS =
     TOP_INCLUDES = -I$(INCROOT) $(TOP_X_INCLUDES)
  PROJECT_DEFINES =

CXXPROJECT_DEFINES =

# ----------------------------------------------------------------------
# start of Imakefile

#
# Copyright (C) 1997 by Marcin Dalecki
#

        DEFINES = -DUNCOMPRESS=\"zcat\"
  SYS_LIBRARIES = -lm
        DEPLIBS = $(DEPXMLIB) $(DEPXTOOLLIB) $(DEPXLIB)
LOCAL_LIBRARIES = $(XMLIB) $(XTOOLLIB) $(XLIB) $(XMEXTRA_LIBS)

# CDEBUGFLAGS = -g -Wall

SRCS=  	main.c display.c fops.c parse.c pix.c tip.c utils.c XpmButton.c 	resource.c

OBJS=  	main.o display.o fops.o parse.o pix.o tip.o utils.o XpmButton.o 	resource.o

 PROGRAM = minfo

all:: minfo

minfo: $(OBJS) $(DEPLIBS)
	$(RM) $@
	$(CC) -o $@ $(LDOPTIONS) $(OBJS)  $(DEPLIBS) $(LDLIBS)  $(LOCAL_LIBRARIES) $(EXTRA_LOAD_FLAGS)

install:: minfo
	@if [ -d $(DESTDIR)$(BINDIR) ]; then set +x; \
	else (set -x; $(MKDIRHIER) $(DESTDIR)$(BINDIR)); fi
	$(INSTALL) $(INSTALLFLAGS) $(INSTPGMFLAGS)  minfo $(DESTDIR)$(BINDIR)/minfo

install.man::
	@echo To install documentation for $(PROGRAM), consult the Release Notes
	@echo and/or README file in the current directory.

depend::
	$(DEPEND) $(DEPENDFLAGS) -- $(ALLDEFINES) $(DEPEND_DEFINES) -- $(SRCS)

lint:
	$(LINT) $(LINTFLAGS) $(SRCS) $(LINTLIBS)
lint1:
	$(LINT) $(LINTFLAGS) $(FILE) $(LINTLIBS)

clean::
	$(RM) $(PROGRAM)

install:: MInfo.ad
	@if [ -d $(DESTDIR)$(XAPPLOADDIR) ]; then set +x; \
	else (set -x; $(MKDIRHIER) $(DESTDIR)$(XAPPLOADDIR)); fi
	$(INSTALL) $(INSTALLFLAGS) $(INSTAPPFLAGS) MInfo.ad $(DESTDIR)$(XAPPLOADDIR)/MInfo

# ----------------------------------------------------------------------
# common rules for all Makefiles - do not edit

.c.i:
	$(RM) $@
	 $(CC) -E $(CFLAGS) $(_NOOP_) $*.c > $@

emptyrule::

clean::
	$(RM) *.CKP *.ln *.BAK *.bak *.o core errs ,* *~ *.a .emacs_* tags TAGS make.log MakeOut  "#"*

Makefile::
	-@if [ -f Makefile ]; then set -x; \
	$(RM) Makefile.bak; $(MV) Makefile Makefile.bak; \
	else exit 0; fi
	$(IMAKE_CMD) -DTOPDIR=$(TOP) -DCURDIR=$(CURRENT_DIR)

tags::
	$(TAGS) -w *.[ch]
	$(TAGS) -xw *.[ch] > TAGS

man_keywords::

# ----------------------------------------------------------------------
# empty rules for directories that do not have SUBDIRS - do not edit

install::
	@echo "install in $(CURRENT_DIR) done"

install.man::
	@echo "install.man in $(CURRENT_DIR) done"

install.linkkit::
	@echo "install.linkkit in $(CURRENT_DIR) done"

Makefiles::

includes::

depend::

# ----------------------------------------------------------------------
# dependencies generated by makedepend

# DO NOT DELETE
main.o: main.c /usr/include/stdlib.h /usr/include/features.h \
 /usr/include/sys/cdefs.h \
 /usr/lib/gcc-lib/i586-linux/2.7.2.3/include/stddef.h \
 /usr/include/errno.h /usr/include/linux/errno.h \
 /usr/include/asm/errno.h /usr/include/alloca.h /usr/include/ctype.h \
 /usr/include/endian.h /usr/include/bytesex.h \
 /usr/X11R6/include/X11/Intrinsic.h /usr/X11R6/include/X11/Xlib.h \
 /usr/include/sys/types.h /usr/include/linux/types.h \
 /usr/include/linux/posix_types.h /usr/include/asm/posix_types.h \
 /usr/include/asm/types.h /usr/include/sys/bitypes.h \
 /usr/X11R6/include/X11/X.h /usr/X11R6/include/X11/Xfuncproto.h \
 /usr/X11R6/include/X11/Xosdefs.h /usr/X11R6/include/X11/Xutil.h \
 /usr/X11R6/include/X11/Xresource.h /usr/include/string.h \
 /usr/X11R6/include/X11/Core.h /usr/X11R6/include/X11/Composite.h \
 /usr/X11R6/include/X11/Constraint.h /usr/X11R6/include/X11/Object.h \
 /usr/X11R6/include/X11/RectObj.h /usr/X11R6/include/X11/StringDefs.h \
 /usr/X11R6/include/X11/Shell.h /usr/X11R6/include/X11/SM/SMlib.h \
 /usr/X11R6/include/X11/SM/SM.h /usr/X11R6/include/X11/ICE/ICElib.h \
 /usr/X11R6/include/X11/ICE/ICE.h /usr/X11R6/include/Xm/MainW.h \
 /usr/X11R6/include/Xm/Xm.h /usr/X11R6/include/X11/Xatom.h \
 /usr/X11R6/include/Xm/XmStrDefs.h /usr/X11R6/include/Xm/VirtKeys.h \
 /usr/X11R6/include/Xm/Transfer.h /usr/X11R6/include/Xm/DragDrop.h \
 /usr/X11R6/include/Xm/DragC.h /usr/X11R6/include/Xm/Display.h \
 /usr/X11R6/include/Xm/DropSMgr.h /usr/X11R6/include/Xm/DragIcon.h \
 /usr/X11R6/include/Xm/DropTrans.h /usr/X11R6/include/Xm/DragOverS.h \
 /usr/X11R6/include/Xm/Primitive.h /usr/X11R6/include/Xm/Manager.h \
 /usr/X11R6/include/Xm/Gadget.h /usr/X11R6/include/Xm/TxtPropCv.h \
 /usr/X11R6/include/Xm/VendorS.h /usr/X11R6/include/Xm/XmIm.h \
 /usr/X11R6/include/Xm/PanedW.h /usr/X11R6/include/Xm/Form.h \
 /usr/X11R6/include/Xm/BulletinB.h /usr/X11R6/include/Xm/Frame.h \
 /usr/X11R6/include/Xm/RowColumn.h /usr/X11R6/include/Xm/PushBG.h \
 /usr/X11R6/include/Xm/PushB.h /usr/X11R6/include/Xm/SeparatoG.h \
 /usr/X11R6/include/Xm/ScrolledW.h /usr/X11R6/include/Xm/List.h \
 /usr/X11R6/include/Xm/Label.h /usr/X11R6/include/Xm/LabelG.h \
 /usr/X11R6/include/Xm/MessageB.h /usr/X11R6/include/Xm/FileSB.h \
 /usr/X11R6/include/Xm/Text.h /usr/include/stdio.h \
 /usr/include/libio.h /usr/include/_G_config.h \
 /usr/X11R6/include/Xm/TextP.h /usr/X11R6/include/Xm/PrimitiveP.h \
 /usr/X11R6/include/Xm/XmP.h /usr/X11R6/include/X11/IntrinsicP.h \
 /usr/X11R6/include/X11/CoreP.h /usr/X11R6/include/X11/CompositeP.h \
 /usr/X11R6/include/X11/ConstrainP.h /usr/X11R6/include/X11/ObjectP.h \
 /usr/X11R6/include/X11/RectObjP.h /usr/X11R6/include/Xm/ColorP.h \
 /usr/X11R6/include/Xm/AccColorT.h /usr/X11R6/include/Xm/BaseClassP.h \
 /usr/X11R6/include/Xm/TextOutP.h /usr/X11R6/include/Xm/TextInP.h \
 /usr/X11R6/include/Xm/TextStrSoP.h /usr/X11R6/include/Xm/TransferT.h \
 /usr/X11R6/include/Xm/TransferP.h /usr/X11R6/include/Xm/SelectioB.h \
 /usr/X11R6/include/Xm/TextF.h /usr/X11R6/include/X11/xpm.h pix.h \
 fops.h parse.h display.h tip.h utils.h XpmButton.h pixmaps/icon.xpm \
 pixmaps/back_arm.xpm pixmaps/back_dis.xpm pixmaps/fwrd_arm.xpm \
 pixmaps/fwrd_dis.xpm pixmaps/prev_arm.xpm pixmaps/prev_dis.xpm \
 pixmaps/next_arm.xpm pixmaps/next_dis.xpm pixmaps/top_arm.xpm \
 pixmaps/top_dis.xpm pixmaps/home.xpm pixmaps/search.xpm \
 pixmaps/vertical.xpm pixmaps/horizontal.xpm pixmaps/dalecki.xpm
display.o: display.c /usr/include/stdlib.h /usr/include/features.h \
 /usr/include/sys/cdefs.h \
 /usr/lib/gcc-lib/i586-linux/2.7.2.3/include/stddef.h \
 /usr/include/errno.h /usr/include/linux/errno.h \
 /usr/include/asm/errno.h /usr/include/alloca.h \
 /usr/X11R6/include/X11/Intrinsic.h /usr/X11R6/include/X11/Xlib.h \
 /usr/include/sys/types.h /usr/include/linux/types.h \
 /usr/include/linux/posix_types.h /usr/include/asm/posix_types.h \
 /usr/include/asm/types.h /usr/include/sys/bitypes.h \
 /usr/X11R6/include/X11/X.h /usr/X11R6/include/X11/Xfuncproto.h \
 /usr/X11R6/include/X11/Xosdefs.h /usr/X11R6/include/X11/Xutil.h \
 /usr/X11R6/include/X11/Xresource.h /usr/include/string.h \
 /usr/X11R6/include/X11/Core.h /usr/X11R6/include/X11/Composite.h \
 /usr/X11R6/include/X11/Constraint.h /usr/X11R6/include/X11/Object.h \
 /usr/X11R6/include/X11/RectObj.h /usr/X11R6/include/X11/StringDefs.h \
 /usr/X11R6/include/X11/Shell.h /usr/X11R6/include/X11/SM/SMlib.h \
 /usr/X11R6/include/X11/SM/SM.h /usr/X11R6/include/X11/ICE/ICElib.h \
 /usr/X11R6/include/X11/ICE/ICE.h /usr/X11R6/include/Xm/MainW.h \
 /usr/X11R6/include/Xm/Xm.h /usr/X11R6/include/X11/Xatom.h \
 /usr/X11R6/include/Xm/XmStrDefs.h /usr/X11R6/include/Xm/VirtKeys.h \
 /usr/X11R6/include/Xm/Transfer.h /usr/X11R6/include/Xm/DragDrop.h \
 /usr/X11R6/include/Xm/DragC.h /usr/X11R6/include/Xm/Display.h \
 /usr/X11R6/include/Xm/DropSMgr.h /usr/X11R6/include/Xm/DragIcon.h \
 /usr/X11R6/include/Xm/DropTrans.h /usr/X11R6/include/Xm/DragOverS.h \
 /usr/X11R6/include/Xm/Primitive.h /usr/X11R6/include/Xm/Manager.h \
 /usr/X11R6/include/Xm/Gadget.h /usr/X11R6/include/Xm/TxtPropCv.h \
 /usr/X11R6/include/Xm/VendorS.h /usr/X11R6/include/Xm/XmIm.h \
 /usr/X11R6/include/Xm/PanedW.h /usr/X11R6/include/Xm/Form.h \
 /usr/X11R6/include/Xm/BulletinB.h /usr/X11R6/include/Xm/RowColumn.h \
 /usr/X11R6/include/Xm/PushBG.h /usr/X11R6/include/Xm/LabelG.h \
 /usr/X11R6/include/Xm/ScrolledW.h /usr/X11R6/include/Xm/List.h \
 /usr/X11R6/include/Xm/Text.h /usr/include/stdio.h \
 /usr/include/libio.h /usr/include/_G_config.h \
 /usr/X11R6/include/Xm/TextP.h /usr/X11R6/include/Xm/PrimitiveP.h \
 /usr/X11R6/include/Xm/XmP.h /usr/X11R6/include/X11/IntrinsicP.h \
 /usr/X11R6/include/X11/CoreP.h /usr/X11R6/include/X11/CompositeP.h \
 /usr/X11R6/include/X11/ConstrainP.h /usr/X11R6/include/X11/ObjectP.h \
 /usr/X11R6/include/X11/RectObjP.h /usr/X11R6/include/Xm/ColorP.h \
 /usr/X11R6/include/Xm/AccColorT.h /usr/X11R6/include/Xm/BaseClassP.h \
 /usr/X11R6/include/Xm/TextOutP.h /usr/X11R6/include/Xm/TextInP.h \
 /usr/X11R6/include/Xm/TextStrSoP.h /usr/X11R6/include/Xm/TransferT.h \
 /usr/X11R6/include/Xm/TransferP.h /usr/X11R6/include/Xm/TextF.h \
 /usr/X11R6/include/Xm/Label.h /usr/X11R6/include/Xm/MessageB.h \
 /usr/X11R6/include/Xm/FileSB.h parse.h display.h fops.h
fops.o: fops.c /usr/include/sys/stat.h /usr/include/features.h \
 /usr/include/sys/cdefs.h /usr/include/sys/types.h \
 /usr/include/linux/types.h /usr/include/linux/posix_types.h \
 /usr/include/asm/posix_types.h /usr/include/asm/types.h \
 /usr/include/sys/bitypes.h /usr/include/linux/stat.h \
 /usr/include/stdio.h /usr/include/libio.h /usr/include/_G_config.h \
 /usr/include/string.h \
 /usr/lib/gcc-lib/i586-linux/2.7.2.3/include/stddef.h \
 /usr/include/stdlib.h /usr/include/errno.h /usr/include/linux/errno.h \
 /usr/include/asm/errno.h /usr/include/alloca.h /usr/include/unistd.h \
 /usr/include/posix_opt.h /usr/include/gnu/types.h \
 /usr/include/confname.h /usr/X11R6/include/Xm/FileSB.h \
 /usr/X11R6/include/Xm/Xm.h /usr/X11R6/include/X11/Intrinsic.h \
 /usr/X11R6/include/X11/Xlib.h /usr/X11R6/include/X11/X.h \
 /usr/X11R6/include/X11/Xfuncproto.h /usr/X11R6/include/X11/Xosdefs.h \
 /usr/X11R6/include/X11/Xutil.h /usr/X11R6/include/X11/Xresource.h \
 /usr/X11R6/include/X11/Core.h /usr/X11R6/include/X11/Composite.h \
 /usr/X11R6/include/X11/Constraint.h /usr/X11R6/include/X11/Object.h \
 /usr/X11R6/include/X11/RectObj.h /usr/X11R6/include/X11/Shell.h \
 /usr/X11R6/include/X11/SM/SMlib.h /usr/X11R6/include/X11/SM/SM.h \
 /usr/X11R6/include/X11/ICE/ICElib.h /usr/X11R6/include/X11/ICE/ICE.h \
 /usr/X11R6/include/X11/Xatom.h /usr/X11R6/include/Xm/XmStrDefs.h \
 /usr/X11R6/include/X11/StringDefs.h /usr/X11R6/include/Xm/VirtKeys.h \
 /usr/X11R6/include/Xm/Transfer.h /usr/X11R6/include/Xm/DragDrop.h \
 /usr/X11R6/include/Xm/DragC.h /usr/X11R6/include/Xm/Display.h \
 /usr/X11R6/include/Xm/DropSMgr.h /usr/X11R6/include/Xm/DragIcon.h \
 /usr/X11R6/include/Xm/DropTrans.h /usr/X11R6/include/Xm/DragOverS.h \
 /usr/X11R6/include/Xm/Primitive.h /usr/X11R6/include/Xm/Manager.h \
 /usr/X11R6/include/Xm/Gadget.h /usr/X11R6/include/Xm/TxtPropCv.h \
 /usr/X11R6/include/Xm/VendorS.h /usr/X11R6/include/Xm/XmIm.h \
 /usr/X11R6/include/Xm/PushB.h /usr/X11R6/include/Xm/Text.h \
 /usr/X11R6/include/Xm/TextP.h /usr/X11R6/include/Xm/PrimitiveP.h \
 /usr/X11R6/include/Xm/XmP.h /usr/X11R6/include/X11/IntrinsicP.h \
 /usr/X11R6/include/X11/CoreP.h /usr/X11R6/include/X11/CompositeP.h \
 /usr/X11R6/include/X11/ConstrainP.h /usr/X11R6/include/X11/ObjectP.h \
 /usr/X11R6/include/X11/RectObjP.h /usr/X11R6/include/Xm/ColorP.h \
 /usr/X11R6/include/Xm/AccColorT.h /usr/X11R6/include/Xm/BaseClassP.h \
 /usr/X11R6/include/Xm/TextOutP.h /usr/X11R6/include/Xm/TextInP.h \
 /usr/X11R6/include/Xm/TextStrSoP.h /usr/X11R6/include/Xm/TransferT.h \
 /usr/X11R6/include/Xm/TransferP.h fops.h parse.h display.h utils.h
parse.o: parse.c /usr/include/stdlib.h /usr/include/features.h \
 /usr/include/sys/cdefs.h \
 /usr/lib/gcc-lib/i586-linux/2.7.2.3/include/stddef.h \
 /usr/include/errno.h /usr/include/linux/errno.h \
 /usr/include/asm/errno.h /usr/include/alloca.h /usr/include/ctype.h \
 /usr/include/endian.h /usr/include/bytesex.h /usr/include/stdio.h \
 /usr/include/libio.h /usr/include/_G_config.h /usr/include/string.h \
 parse.h /usr/X11R6/include/Xm/Text.h /usr/X11R6/include/Xm/Xm.h \
 /usr/X11R6/include/X11/Intrinsic.h /usr/X11R6/include/X11/Xlib.h \
 /usr/include/sys/types.h /usr/include/linux/types.h \
 /usr/include/linux/posix_types.h /usr/include/asm/posix_types.h \
 /usr/include/asm/types.h /usr/include/sys/bitypes.h \
 /usr/X11R6/include/X11/X.h /usr/X11R6/include/X11/Xfuncproto.h \
 /usr/X11R6/include/X11/Xosdefs.h /usr/X11R6/include/X11/Xutil.h \
 /usr/X11R6/include/X11/Xresource.h /usr/X11R6/include/X11/Core.h \
 /usr/X11R6/include/X11/Composite.h \
 /usr/X11R6/include/X11/Constraint.h /usr/X11R6/include/X11/Object.h \
 /usr/X11R6/include/X11/RectObj.h /usr/X11R6/include/X11/Shell.h \
 /usr/X11R6/include/X11/SM/SMlib.h /usr/X11R6/include/X11/SM/SM.h \
 /usr/X11R6/include/X11/ICE/ICElib.h /usr/X11R6/include/X11/ICE/ICE.h \
 /usr/X11R6/include/X11/Xatom.h /usr/X11R6/include/Xm/XmStrDefs.h \
 /usr/X11R6/include/X11/StringDefs.h /usr/X11R6/include/Xm/VirtKeys.h \
 /usr/X11R6/include/Xm/Transfer.h /usr/X11R6/include/Xm/DragDrop.h \
 /usr/X11R6/include/Xm/DragC.h /usr/X11R6/include/Xm/Display.h \
 /usr/X11R6/include/Xm/DropSMgr.h /usr/X11R6/include/Xm/DragIcon.h \
 /usr/X11R6/include/Xm/DropTrans.h /usr/X11R6/include/Xm/DragOverS.h \
 /usr/X11R6/include/Xm/Primitive.h /usr/X11R6/include/Xm/Manager.h \
 /usr/X11R6/include/Xm/Gadget.h /usr/X11R6/include/Xm/TxtPropCv.h \
 /usr/X11R6/include/Xm/VendorS.h /usr/X11R6/include/Xm/XmIm.h
pix.o: pix.c /usr/X11R6/include/X11/Intrinsic.h \
 /usr/X11R6/include/X11/Xlib.h /usr/include/sys/types.h \
 /usr/include/linux/types.h /usr/include/linux/posix_types.h \
 /usr/include/asm/posix_types.h /usr/include/asm/types.h \
 /usr/include/sys/bitypes.h /usr/X11R6/include/X11/X.h \
 /usr/X11R6/include/X11/Xfuncproto.h /usr/X11R6/include/X11/Xosdefs.h \
 /usr/lib/gcc-lib/i586-linux/2.7.2.3/include/stddef.h \
 /usr/X11R6/include/X11/Xutil.h /usr/X11R6/include/X11/Xresource.h \
 /usr/include/string.h /usr/include/features.h \
 /usr/include/sys/cdefs.h /usr/X11R6/include/X11/Core.h \
 /usr/X11R6/include/X11/Composite.h \
 /usr/X11R6/include/X11/Constraint.h /usr/X11R6/include/X11/Object.h \
 /usr/X11R6/include/X11/RectObj.h /usr/X11R6/include/X11/xpm.h \
 /usr/X11R6/include/Xm/Xm.h /usr/X11R6/include/X11/Shell.h \
 /usr/X11R6/include/X11/SM/SMlib.h /usr/X11R6/include/X11/SM/SM.h \
 /usr/X11R6/include/X11/ICE/ICElib.h /usr/X11R6/include/X11/ICE/ICE.h \
 /usr/X11R6/include/X11/Xatom.h /usr/X11R6/include/Xm/XmStrDefs.h \
 /usr/X11R6/include/X11/StringDefs.h /usr/X11R6/include/Xm/VirtKeys.h \
 /usr/X11R6/include/Xm/Transfer.h /usr/X11R6/include/Xm/DragDrop.h \
 /usr/X11R6/include/Xm/DragC.h /usr/X11R6/include/Xm/Display.h \
 /usr/X11R6/include/Xm/DropSMgr.h /usr/X11R6/include/Xm/DragIcon.h \
 /usr/X11R6/include/Xm/DropTrans.h /usr/X11R6/include/Xm/DragOverS.h \
 /usr/X11R6/include/Xm/Primitive.h /usr/X11R6/include/Xm/Manager.h \
 /usr/X11R6/include/Xm/Gadget.h /usr/X11R6/include/Xm/TxtPropCv.h \
 /usr/X11R6/include/Xm/VendorS.h /usr/X11R6/include/Xm/XmIm.h \
 /usr/include/xpm.h
tip.o: tip.c /usr/include/unistd.h /usr/include/features.h \
 /usr/include/sys/cdefs.h /usr/include/posix_opt.h \
 /usr/include/gnu/types.h /usr/include/linux/posix_types.h \
 /usr/include/asm/posix_types.h \
 /usr/lib/gcc-lib/i586-linux/2.7.2.3/include/stddef.h \
 /usr/include/confname.h /usr/include/sys/types.h \
 /usr/include/linux/types.h /usr/include/asm/types.h \
 /usr/include/sys/bitypes.h /usr/include/signal.h \
 /usr/include/linux/signal.h /usr/include/asm/signal.h \
 /usr/include/stdio.h /usr/include/libio.h /usr/include/_G_config.h \
 /usr/X11R6/include/X11/IntrinsicP.h \
 /usr/X11R6/include/X11/Intrinsic.h /usr/X11R6/include/X11/Xlib.h \
 /usr/X11R6/include/X11/X.h /usr/X11R6/include/X11/Xfuncproto.h \
 /usr/X11R6/include/X11/Xosdefs.h /usr/X11R6/include/X11/Xutil.h \
 /usr/X11R6/include/X11/Xresource.h /usr/include/string.h \
 /usr/X11R6/include/X11/Core.h /usr/X11R6/include/X11/Composite.h \
 /usr/X11R6/include/X11/Constraint.h /usr/X11R6/include/X11/Object.h \
 /usr/X11R6/include/X11/RectObj.h /usr/X11R6/include/X11/CoreP.h \
 /usr/X11R6/include/X11/CompositeP.h \
 /usr/X11R6/include/X11/ConstrainP.h /usr/X11R6/include/X11/ObjectP.h \
 /usr/X11R6/include/X11/RectObjP.h /usr/X11R6/include/X11/StringDefs.h \
 /usr/X11R6/include/Xm/XmP.h /usr/X11R6/include/Xm/Xm.h \
 /usr/X11R6/include/X11/Shell.h /usr/X11R6/include/X11/SM/SMlib.h \
 /usr/X11R6/include/X11/SM/SM.h /usr/X11R6/include/X11/ICE/ICElib.h \
 /usr/X11R6/include/X11/ICE/ICE.h /usr/X11R6/include/X11/Xatom.h \
 /usr/X11R6/include/Xm/XmStrDefs.h /usr/X11R6/include/Xm/VirtKeys.h \
 /usr/X11R6/include/Xm/Transfer.h /usr/X11R6/include/Xm/DragDrop.h \
 /usr/X11R6/include/Xm/DragC.h /usr/X11R6/include/Xm/Display.h \
 /usr/X11R6/include/Xm/DropSMgr.h /usr/X11R6/include/Xm/DragIcon.h \
 /usr/X11R6/include/Xm/DropTrans.h /usr/X11R6/include/Xm/DragOverS.h \
 /usr/X11R6/include/Xm/Primitive.h /usr/X11R6/include/Xm/Manager.h \
 /usr/X11R6/include/Xm/Gadget.h /usr/X11R6/include/Xm/TxtPropCv.h \
 /usr/X11R6/include/Xm/VendorS.h /usr/X11R6/include/Xm/XmIm.h \
 /usr/X11R6/include/Xm/ColorP.h /usr/X11R6/include/Xm/AccColorT.h \
 /usr/X11R6/include/Xm/BaseClassP.h /usr/X11R6/include/Xm/PushB.h \
 /usr/X11R6/include/X11/ShellP.h /usr/X11R6/include/X11/VendorP.h \
 /usr/X11R6/include/X11/Vendor.h tip.h
utils.o: utils.c /usr/include/stdlib.h /usr/include/features.h \
 /usr/include/sys/cdefs.h \
 /usr/lib/gcc-lib/i586-linux/2.7.2.3/include/stddef.h \
 /usr/include/errno.h /usr/include/linux/errno.h \
 /usr/include/asm/errno.h /usr/include/alloca.h \
 /usr/X11R6/include/X11/Intrinsic.h /usr/X11R6/include/X11/Xlib.h \
 /usr/include/sys/types.h /usr/include/linux/types.h \
 /usr/include/linux/posix_types.h /usr/include/asm/posix_types.h \
 /usr/include/asm/types.h /usr/include/sys/bitypes.h \
 /usr/X11R6/include/X11/X.h /usr/X11R6/include/X11/Xfuncproto.h \
 /usr/X11R6/include/X11/Xosdefs.h /usr/X11R6/include/X11/Xutil.h \
 /usr/X11R6/include/X11/Xresource.h /usr/include/string.h \
 /usr/X11R6/include/X11/Core.h /usr/X11R6/include/X11/Composite.h \
 /usr/X11R6/include/X11/Constraint.h /usr/X11R6/include/X11/Object.h \
 /usr/X11R6/include/X11/RectObj.h /usr/X11R6/include/X11/StringDefs.h \
 /usr/X11R6/include/X11/Shell.h /usr/X11R6/include/X11/SM/SMlib.h \
 /usr/X11R6/include/X11/SM/SM.h /usr/X11R6/include/X11/ICE/ICElib.h \
 /usr/X11R6/include/X11/ICE/ICE.h /usr/X11R6/include/Xm/MessageB.h \
 /usr/X11R6/include/Xm/Xm.h /usr/X11R6/include/X11/Xatom.h \
 /usr/X11R6/include/Xm/XmStrDefs.h /usr/X11R6/include/Xm/VirtKeys.h \
 /usr/X11R6/include/Xm/Transfer.h /usr/X11R6/include/Xm/DragDrop.h \
 /usr/X11R6/include/Xm/DragC.h /usr/X11R6/include/Xm/Display.h \
 /usr/X11R6/include/Xm/DropSMgr.h /usr/X11R6/include/Xm/DragIcon.h \
 /usr/X11R6/include/Xm/DropTrans.h /usr/X11R6/include/Xm/DragOverS.h \
 /usr/X11R6/include/Xm/Primitive.h /usr/X11R6/include/Xm/Manager.h \
 /usr/X11R6/include/Xm/Gadget.h /usr/X11R6/include/Xm/TxtPropCv.h \
 /usr/X11R6/include/Xm/VendorS.h /usr/X11R6/include/Xm/XmIm.h \
 /usr/X11R6/include/Xm/ToggleB.h /usr/X11R6/include/Xm/PushB.h \
 /usr/X11R6/include/Xm/PushBG.h /usr/X11R6/include/Xm/Form.h \
 /usr/X11R6/include/Xm/BulletinB.h /usr/X11R6/include/Xm/Label.h \
 /usr/X11R6/include/Xm/TextF.h /usr/X11R6/include/Xm/Text.h \
 /usr/include/stdio.h /usr/include/libio.h /usr/include/_G_config.h \
 /usr/X11R6/include/Xm/TextP.h /usr/X11R6/include/Xm/PrimitiveP.h \
 /usr/X11R6/include/Xm/XmP.h /usr/X11R6/include/X11/IntrinsicP.h \
 /usr/X11R6/include/X11/CoreP.h /usr/X11R6/include/X11/CompositeP.h \
 /usr/X11R6/include/X11/ConstrainP.h /usr/X11R6/include/X11/ObjectP.h \
 /usr/X11R6/include/X11/RectObjP.h /usr/X11R6/include/Xm/ColorP.h \
 /usr/X11R6/include/Xm/AccColorT.h /usr/X11R6/include/Xm/BaseClassP.h \
 /usr/X11R6/include/Xm/TextOutP.h /usr/X11R6/include/Xm/TextInP.h \
 /usr/X11R6/include/Xm/TextStrSoP.h /usr/X11R6/include/Xm/TransferT.h \
 /usr/X11R6/include/Xm/TransferP.h fops.h parse.h display.h utils.h
XpmButton.o: XpmButton.c /usr/X11R6/include/Xm/Label.h \
 /usr/X11R6/include/Xm/Xm.h /usr/X11R6/include/X11/Intrinsic.h \
 /usr/X11R6/include/X11/Xlib.h /usr/include/sys/types.h \
 /usr/include/linux/types.h /usr/include/linux/posix_types.h \
 /usr/include/asm/posix_types.h /usr/include/asm/types.h \
 /usr/include/sys/bitypes.h /usr/X11R6/include/X11/X.h \
 /usr/X11R6/include/X11/Xfuncproto.h /usr/X11R6/include/X11/Xosdefs.h \
 /usr/lib/gcc-lib/i586-linux/2.7.2.3/include/stddef.h \
 /usr/X11R6/include/X11/Xutil.h /usr/X11R6/include/X11/Xresource.h \
 /usr/include/string.h /usr/include/features.h \
 /usr/include/sys/cdefs.h /usr/X11R6/include/X11/Core.h \
 /usr/X11R6/include/X11/Composite.h \
 /usr/X11R6/include/X11/Constraint.h /usr/X11R6/include/X11/Object.h \
 /usr/X11R6/include/X11/RectObj.h /usr/X11R6/include/X11/Shell.h \
 /usr/X11R6/include/X11/SM/SMlib.h /usr/X11R6/include/X11/SM/SM.h \
 /usr/X11R6/include/X11/ICE/ICElib.h /usr/X11R6/include/X11/ICE/ICE.h \
 /usr/X11R6/include/X11/Xatom.h /usr/X11R6/include/Xm/XmStrDefs.h \
 /usr/X11R6/include/X11/StringDefs.h /usr/X11R6/include/Xm/VirtKeys.h \
 /usr/X11R6/include/Xm/Transfer.h /usr/X11R6/include/Xm/DragDrop.h \
 /usr/X11R6/include/Xm/DragC.h /usr/X11R6/include/Xm/Display.h \
 /usr/X11R6/include/Xm/DropSMgr.h /usr/X11R6/include/Xm/DragIcon.h \
 /usr/X11R6/include/Xm/DropTrans.h /usr/X11R6/include/Xm/DragOverS.h \
 /usr/X11R6/include/Xm/Primitive.h /usr/X11R6/include/Xm/Manager.h \
 /usr/X11R6/include/Xm/Gadget.h /usr/X11R6/include/Xm/TxtPropCv.h \
 /usr/X11R6/include/Xm/VendorS.h /usr/X11R6/include/Xm/XmIm.h \
 /usr/X11R6/include/Xm/PushB.h /usr/X11R6/include/Xm/LabelG.h \
 /usr/X11R6/include/Xm/PushBG.h /usr/X11R6/include/X11/xpm.h \
 XpmButton.h resource.h
resource.o: resource.c /usr/include/string.h /usr/include/features.h \
 /usr/include/sys/cdefs.h \
 /usr/lib/gcc-lib/i586-linux/2.7.2.3/include/stddef.h \
 /usr/include/ctype.h /usr/include/endian.h /usr/include/bytesex.h \
 /usr/X11R6/include/X11/StringDefs.h resource.h \
 /usr/X11R6/include/Xm/Xm.h /usr/X11R6/include/X11/Intrinsic.h \
 /usr/X11R6/include/X11/Xlib.h /usr/include/sys/types.h \
 /usr/include/linux/types.h /usr/include/linux/posix_types.h \
 /usr/include/asm/posix_types.h /usr/include/asm/types.h \
 /usr/include/sys/bitypes.h /usr/X11R6/include/X11/X.h \
 /usr/X11R6/include/X11/Xfuncproto.h /usr/X11R6/include/X11/Xosdefs.h \
 /usr/X11R6/include/X11/Xutil.h /usr/X11R6/include/X11/Xresource.h \
 /usr/X11R6/include/X11/Core.h /usr/X11R6/include/X11/Composite.h \
 /usr/X11R6/include/X11/Constraint.h /usr/X11R6/include/X11/Object.h \
 /usr/X11R6/include/X11/RectObj.h /usr/X11R6/include/X11/Shell.h \
 /usr/X11R6/include/X11/SM/SMlib.h /usr/X11R6/include/X11/SM/SM.h \
 /usr/X11R6/include/X11/ICE/ICElib.h /usr/X11R6/include/X11/ICE/ICE.h \
 /usr/X11R6/include/X11/Xatom.h /usr/X11R6/include/Xm/XmStrDefs.h \
 /usr/X11R6/include/Xm/VirtKeys.h /usr/X11R6/include/Xm/Transfer.h \
 /usr/X11R6/include/Xm/DragDrop.h /usr/X11R6/include/Xm/DragC.h \
 /usr/X11R6/include/Xm/Display.h /usr/X11R6/include/Xm/DropSMgr.h \
 /usr/X11R6/include/Xm/DragIcon.h /usr/X11R6/include/Xm/DropTrans.h \
 /usr/X11R6/include/Xm/DragOverS.h /usr/X11R6/include/Xm/Primitive.h \
 /usr/X11R6/include/Xm/Manager.h /usr/X11R6/include/Xm/Gadget.h \
 /usr/X11R6/include/Xm/TxtPropCv.h /usr/X11R6/include/Xm/VendorS.h \
 /usr/X11R6/include/Xm/XmIm.h
