minfo:	resource.c XpmButton.c file_ops.c parse.c  utils.c display.c main.c pix.c tip.c
	gcc -o $@ -I/root/tmp/lesstif/include/Motif-1.2/  $^ -lm -L/root/tmp/lesstif/lib/Xm/ -lXm -L/usr/X11R6/lib/  -lXpm -lXt -lSM -lICE -lXext -lX11  
 
